apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayployment
  labels:
    team: tarismadevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service    
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:        
        - image: muhammedali55/yarismauygulamasigateway:v001
          name:  podgateway
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 80      
          env:     
            - name: AUTHURL
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: gateway_auth_url
            - name: MAINURL
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: gateway_main_url
            - name: USERURL
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: gateway_user_url