apiVersion: v1

kind: Service

metadata:
  name: loadbalancer-gateway

spec:
  selector:
    app: gateway-service

  type: LoadBalancer

  ports:
    - name: gateway-service

      port: 80

      targetPort: 80
