apiVersion: v1

kind: Service

metadata:
  name: loadbalancer-main

spec:
  selector:
    app: main-service

  type: ClusterIP

  ports:
    - name: main-service

      port: 9092

      targetPort: 9092
