apiVersion: v1

kind: Service

metadata:
  name: loadbalancer-user

spec:
  selector:
    app: user-service

  type: ClusterIP

  ports:
    - name: user-service

      port: 9091

      targetPort: 9091
