apiVersion: v1

kind: Service

metadata:
  name: loadbalancer-auth

spec:
  selector:
    app: auth-service

  type: ClusterIP

  ports:
    - name: auth-service

      port: 9090

      targetPort: 9090
