server:
  port: 9093
spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: main-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/YarismaDB"
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
raceapplication:
  url:
    auth: http://localhost:9090
    main: http://localhost:9093
    user: http://localhost:9091