server:
  port: 9091
logging:
  level:
    root: WARN
    org.ysfyrdmcl: DEBUG
    org.springframework: INFO
  file:
    name: user-service-application.log
    max-size: 1MB
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: yusuf
    password: 12345
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: user-service
#  redis:
#    host: localhost
#    port: 6379
  datasource:
    url: "jdbc:postgresql://localhost:5432/YarismaDB"
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
raceapplication:
  url:
    auth: http://localhost:9090
    main: http://localhost:9093
    user: http://localhost:9091