server:
  port: 8888
spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configyml
  application:
    name: config-server
  profiles:
    active: native